/*
 * This source file was generated by the Gradle 'init' task
 */
package dataset.generator.logistics2;

import java.io.File;
import java.io.FileWriter;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoField;
import java.time.temporal.TemporalAccessor;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.json.JSONArray;
import org.json.JSONObject;

class LogisticsDatasetGenerator2 {

    private static final String CAMUNDA_BASE_URL = "http://localhost:8080/engine-rest";
    private static final String PROCESS_DEFINITION_KEY = "DistributionCenterTest";
    private static final String CAMUNDA_TS = "yyyy-MM-dd'T'HH:mm:ss.SSSZ";

    private List<HashMap<Long,Float>> containerTemp=new ArrayList<HashMap<Long,Float>>();
    private List<HashMap<Long,Float>> containerHum=new ArrayList<HashMap<Long,Float>>();
    private List<HashMap<Long,Float>> refrTemp=new ArrayList<HashMap<Long,Float>>();
    private List<HashMap<Long,Float>> refrHum=new ArrayList<HashMap<Long,Float>>();

    public void generateDataSet() {
         
         try{
            
            InputStream camunda_logs = LogisticsDatasetGenerator2.class
                .getClassLoader()
                .getResourceAsStream("logistics2/camunda.json");

            if (camunda_logs == null) {
                throw new RuntimeException("Camunda File not found in resources");
            }

            InputStream iot_http_logs = LogisticsDatasetGenerator2.class
                .getClassLoader()
                .getResourceAsStream("logistics2/iot_data_http.json");  

            if (iot_http_logs == null) {
                throw new RuntimeException("IoT HTTP File not found in resources");
            }

            InputStream iot_csv_hum_logs = LogisticsDatasetGenerator2.class
                .getClassLoader()
                .getResourceAsStream("logistics2/humidity.csv");  

            if (iot_csv_hum_logs == null) {
                throw new RuntimeException("IoT CV Humidity File not found in resources");
            }

             InputStream iot_csv_temp_logs = LogisticsDatasetGenerator2.class
                .getClassLoader()
                .getResourceAsStream("logistics2/temperature.csv");  

            if (iot_csv_temp_logs == null) {
                throw new RuntimeException("IoT CSV Temperature File not found in resources");
            }

            // Parse Camunda JSON
            String jsonText = new String(camunda_logs.readAllBytes(), StandardCharsets.UTF_8);
            JSONArray camundaJson = new JSONArray(jsonText);

            // Parse IoT JSON
            String jsonText2 = new String(iot_http_logs.readAllBytes(), StandardCharsets.UTF_8);
            JSONArray httpData = new JSONArray(jsonText2);

            FileWriter file = new FileWriter("processedHTTPIoT.csv");
            for(int i=0;i<httpData .length();i++){
                JSONObject data=httpData .getJSONObject(i);
                long timeSt=TimeUtils.parseTimeStamp("dd/MM/yyyy HH:mm:ss", data.getString("timeStamp")).toEpochMilli();
                 String row=timeSt+","; 
                switch(data.getString("id")){
                    case "sn-hum-538474":
                                        HashMap<Long,Float> valueH=new HashMap<Long,Float>();
                                        valueH.put(timeSt, data.getFloat("humidity"));
                                        refrHum.add(valueH);
                                        row+="refrigerator_humidity_sensor,"+data.getFloat("humidity")+"\n";
                                         break;
                    case "sn-tmp-142037":
                                         HashMap<Long,Float> valueT=new HashMap<Long,Float>();
                                        valueT.put(timeSt, data.getFloat("temperature"));
                                        refrTemp.add(valueT);
                                        row+="refrigerator_temperature_sensor,"+data.getFloat("temperature")+"\n";
                }
                file.write(row);
                file.flush();
            }
            file.close();

            // Parse CSV Temperature
            String tempCSV= new String(iot_csv_temp_logs.readAllBytes(), StandardCharsets.UTF_8);
            String rows[]=tempCSV.split("\n");
    
            FileWriter file2 = new FileWriter("processedTempCSV.csv");
            for(int i=1;i<rows.length;i++){
                String cols[]=rows[i].split(",");
                long timeSt=TimeUtils.parseTimeStamp("d MMM uuuu HH:mm:ss z", cols[3]).toEpochMilli();
                HashMap<Long,Float> valueT=new HashMap<Long,Float>();
                valueT.put(timeSt, Float.parseFloat(cols[2]));
                containerTemp.add(valueT);
                String row=timeSt+","+Float.parseFloat(cols[2])+"\n"; 
                file2.write(row);
                file2.flush();
            }
            file2.close();
   
            // Parse CSV Humidity
            String humCSV= new String(iot_csv_hum_logs.readAllBytes(), StandardCharsets.UTF_8);
            String rows2[]=humCSV.split("\n");

            FileWriter file3 = new FileWriter("processedHumCSV.csv");
            for(int i=1;i<rows2.length;i++){
                String cols2[]=rows2[i].split(",");
                long timeSt=TimeUtils.parseTimeStamp("d MMM uuuu HH:mm:ss z", cols2[3]).toEpochMilli();
                HashMap<Long,Float> valueH=new HashMap<Long,Float>();
                valueH.put(timeSt, Float.parseFloat(cols2[2]));
                containerHum.add(valueH);
                String row=timeSt+","+Float.parseFloat(cols2[2])+"\n"; 
                file3.write(row);
                file3.flush();
            }
            file3.close();
 
            String instanceId="";
            HashMap<String,ArrayList<JSONObject>> instances= new HashMap<String,ArrayList<JSONObject>>();
            for(int i=0;i<camundaJson.length();i++){
                JSONObject camundaActivity=camundaJson.getJSONObject(i);

                if(camundaActivity.getString("processDefinitionKey").equals(PROCESS_DEFINITION_KEY)){
                    if(!camundaActivity.getString("processInstanceId").equals(instanceId)){
                        instanceId=camundaActivity.getString("processInstanceId");

                        ArrayList<JSONObject> activities= new ArrayList<JSONObject>();
                        activities.add(camundaActivity);
                        instances.put(instanceId, activities);

                    }else{
                         instances.get(instanceId).add(camundaActivity);
                    }
                }
            }

          
            processInstances(instances);


        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    

    private double avgTemp(String source, long starting, long end){
        
        float sum=0;
        int num=0;

        long window=end-starting;
        while(num==0){
            switch(source){
                case "container":   for(HashMap<Long,Float> value: containerTemp){
                                        long timestamp=value.keySet().iterator().next();
                                        if(timestamp>=starting && timestamp<=end){
                                            sum+=value.get(timestamp);
                                            num++;
                                        } 
                                    }
                                    break;
                case "refrigerator": for(HashMap<Long,Float> value: refrTemp){
                                        long timestamp=value.keySet().iterator().next();
                                        if(timestamp>=starting && timestamp<=end){
                                            sum+=value.get(timestamp);
                                            num++;
                                        } 
                                    }   
                                    break;
            }
            starting-=window;
        }
    
        return Math.round((sum/num) * 100.0) / 100.0;
    }

    private double avgHum(String source, long starting, long end){
        
        float sum=0;
        int num=0;

        long window=end-starting;
        while(num==0){
            switch(source){
                case "container":   for(HashMap<Long,Float> value: containerHum){
                                        long timestamp=value.keySet().iterator().next();
                                        if(timestamp>=starting && timestamp<=end){
                                            sum+=value.get(timestamp);
                                            num++;
                                        } 
                                    }
                                    break;
                case "refrigerator": for(HashMap<Long,Float> value: refrHum){
                                        long timestamp=value.keySet().iterator().next();
                                        if(timestamp>=starting && timestamp<=end){
                                            sum+=value.get(timestamp);
                                            num++;
                                        } 
                                    }   
                                    break;               
            }
            starting-=window;
        }
    
        return Math.round((sum/num) * 100.0) / 100.0;
    }


    private void processInstances(HashMap<String,ArrayList<JSONObject>> instances){
        System.out.println("INST,PI,QF,QC,D,QED,ST,CTB,CHB,CTD,CHD,RT,RH,B");
        for(String instance: instances.keySet()){
            HashMap<String,Object> row=new  HashMap<String,Object>();
            ArrayList<JSONObject> activities=instances.get(instance);

            Instant evaluationCompleted=null;

            for(JSONObject activity: activities){
                String activityId=activity.getString("activityId");

                if(activityId.indexOf("evaluateQualityTask")>=0){
                    String activityInstanceId=activity.getString("id");
                    //crearJSON(activityInstanceId);
                    JSONArray activityVars=getJSONActivityVars(activityInstanceId);

                    for(int i=0;i<activityVars.length();i++){
                        JSONObject var=activityVars.getJSONObject(i);
                        if(var.getString("type").equals("variableUpdate")){
                            if(var.getString("variableName").equals("palletId")){
                                row.put("PI", var.getString("value"));
                            }else if(var.getString("variableName").equals("qualityFirmness")){
                                row.put("QF", var.getString("value"));
                            }else if(var.getString("variableName").equals("qualityColor")){
                                row.put("QC", var.getString("value"));
                            }else if(var.getString("variableName").equals("qualityDamages")){
                                row.put("D", var.getString("value"));
                            }
                        }
                    }

                    Instant startTime=TimeUtils.parseTimeStamp(CAMUNDA_TS, activity.getString("startTime"));
                    Instant endTime=TimeUtils.parseTimeStamp(CAMUNDA_TS, activity.getString("endTime"));

                    double duration=Math.round((endTime.toEpochMilli()-startTime.toEpochMilli()) * 100.0) / 100.0;

                    row.put("QED", duration);

                    
                   double avgTempBefore=avgTemp("container",startTime.toEpochMilli()-60000,startTime.toEpochMilli());
                   row.put("CTB", avgTempBefore);


                   double avgHumBefore=avgHum("container",startTime.toEpochMilli()-60000,startTime.toEpochMilli());
                   row.put("CHB", avgHumBefore);

                   double avgTempDuring=avgTemp("container",startTime.toEpochMilli(),endTime.toEpochMilli());
                   row.put("CTD", avgTempDuring);

                  double avgHumDuring=avgHum("container",startTime.toEpochMilli(),endTime.toEpochMilli());
                   row.put("CHD", avgHumDuring);

                    evaluationCompleted=endTime;
                
                }
                else if(activityId.indexOf("selectSampleMessage")>=0){
                      if(evaluationCompleted!=null){
                        Instant startTime=TimeUtils.parseTimeStamp(CAMUNDA_TS, activity.getString("endTime"));
                        double duration=Math.round((startTime.toEpochMilli()-evaluationCompleted.toEpochMilli()) * 100.0) / 100.0;
                        row.put("ST", duration);

                        double refrTemp=avgTemp("refrigerator",evaluationCompleted.toEpochMilli(),startTime.toEpochMilli());
                        row.put("RT", refrTemp);

                        double refrHum=avgHum("refrigerator",evaluationCompleted.toEpochMilli(),startTime.toEpochMilli());
                        row.put("RH", refrHum);
                     
                    }
                }else{
                    if(activityId.indexOf("bacteriaCondition")>=0){

                        String activityInstanceId=activity.getString("id");
                        //crearJSON(activityInstanceId);
                        JSONArray activityVars=getJSONActivityVars(activityInstanceId);

                        for(int i=0;i<activityVars.length();i++){
                            JSONObject var=activityVars.getJSONObject(i);
                            if(var.getString("type").equals("variableUpdate")){
                                row.put("B", var.getString("value"));
                            }
                        } 
                
                    }
                }
            }
            System.out.println(instance+","+row.get("PI")+","+row.get("QF")+","+row.get("QC")+","+row.get("D")+","+row.get("QED")+","+row.get("ST")+","+row.get("CTB")+","+row.get("CHB")+","+row.get("CTD")+","+row.get("CHD")+","+row.get("RT")+","+row.get("RH")+","+row.get("B"));
        }

        System.out.println(instances.keySet().size());
    }


    private JSONArray getJSONActivityVars(String activityInstanceId){
        try (InputStream is = LogisticsDatasetGenerator2.class
                .getClassLoader()
                .getResourceAsStream("logistics2/activities/"+activityInstanceId+".json")) {

            if (is == null) {
                throw new RuntimeException("Activity File for "+activityInstanceId+" not found in resources");
            }

            // Convert InputStream to String
            String jsonText = new String(is.readAllBytes(), StandardCharsets.UTF_8);

            // Parse JSON
            JSONArray activityJson = new JSONArray(jsonText);

            return activityJson;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
       
    }


    private void crearJSON(String activityInstanceId){
        URI uri = URI.create(CAMUNDA_BASE_URL+ "/history/detail?activityInstanceId="+activityInstanceId);

        HttpRequest req = HttpRequest.newBuilder()
            .uri(uri)
            .GET()
            .timeout(Duration.ofSeconds(15))
            .header("Accept", "application/json")
            .build();

        HttpClient http = HttpClient.newBuilder()
                    .connectTimeout(Duration.ofSeconds(5))
                    .build();
        
        
        try{
            HttpResponse<String> resp = http.send(req, HttpResponse.BodyHandlers.ofString());
            String filePath = "output/"+activityInstanceId+".json";
            
            File dir = new File("output");
            if (!dir.exists()) {
                dir.mkdirs();
            }
            FileWriter file = new FileWriter(filePath);
            file.write(resp.body()); // indentado bonito
            file.close();
 
        }catch(Exception e){
                e.printStackTrace();
        }
    }


    public static void main(String[] args) {
        new LogisticsDatasetGenerator2().generateDataSet();
    }
}



class TimeUtils {
    public static Instant parseTimeStamp(String pattern, String value){
        DateTimeFormatter fmt =
        DateTimeFormatter.ofPattern(pattern, Locale.ENGLISH);

        TemporalAccessor ta = fmt.parse(value);

        // If the timestamp contains an offset / zone → preserve it
        if (ta.isSupported(ChronoField.OFFSET_SECONDS)) {
            return OffsetDateTime.from(ta).toInstant();
        }

        // Otherwise, treat it as local time in Europe/Madrid
        LocalDateTime ldt = LocalDateTime.from(ta);
        return ldt.atZone(ZoneId.of("Europe/Madrid")).toInstant();
    }

}
